name: ci-golang-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20
      # - run: go test
      #- run: go run ./cmd/main.go
      # - name: installing dependencies
        # run: |
        #   go get github.com/lyracampos/go-gRPC/internal/database
      - name: run app
        run: go run main.go
