name: ci-golang-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.4
      - name: go version
        run: go version
      - name: run app
        run: go run ./cmd/main.go
